spring:
  profiles:
    active: @active.spring.profile@
  jpa:
    hibernate:
      naming:
        physical-strategy: com.designwright.discord.discordscape.data.persistence.DataPhysicalNamingStrategy
discord:
  api-token: ${discord.api.token:}
logging:
  level:
    root: ERROR
    com.designwright: INFO
  pattern:
    console: "[%d{yyyy-MM-dd HH:mm:ss}] %-15t|%-4marker| - %m%n"