spring:
  profiles:
    active: @active.spring.profile@
  jpa:
    hibernate:
      naming:
        physical-strategy: com.designwright.discord.mudbot.data.persistence.DataPhysicalNamingStrategy
discord:
  api-token: NjMwMjEwNDg2NzEzMDU3Mjgy.XsXaig._9SfAJw0apRtXG7rc9m0Xw0odeM
logging:
  level:
    root: ERROR
    com.designwright: INFO
  pattern:
    console: "[%d{yyyy-MM-dd HH:mm:ss}] %-15t|%-4marker| - %m%n"